
# imagen
services:    
  # Servidor de la aplicacion  
  parprimo:    
    # Imagen a desplegar. En caso de que no 
    # se encuentre en el sistema Host, lo intentará buscar en Dockerhub
    image: javaapp:nc
    
    # Nombre del contenedor
    container_name: servidor

    # A continuacion declaramos los puertos de nuestra aplicacion.
    # Esto permite asociar un puerto del Host con el puerto del contenedor
    # Formato <HOST>:<CONTENEDOR>
    ports: 
      - "3000:3000"
    
    # Seguidamente definimos las variables del entorno. En nuestro caso
    # definimos el puerto. Estas variables tambien se pueden cargar de un
    # .env ya existente
    environment:
      - PORT=3000

    # Red
    networks:
      - red_interna

# Redes
networks:
  red_interna: {}

